# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
        interval: "weekly"
    commit-message:
        prefix: ":seedling:"

  # Main Go module
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: ":seedling:"
    groups:
      dependencies:
        patterns:
          - "*"
    ignore:
      # Ignore Cluster-API as its upgraded manually.
      - dependency-name: "sigs.k8s.io/cluster-api*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      # Ignore controller-runtime as its upgraded manually.
      - dependency-name: "sigs.k8s.io/controller-runtime"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      # Ignore k8s and its transitives modules as they are upgraded manually together with controller-runtime.
      - dependency-name: "k8s.io/*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      - dependency-name: "go.etcd.io/*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      - dependency-name: "google.golang.org/grpc"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
      # Bumping the kustomize API independently can break compatibility with client-go as they share k8s.io/kube-openapi as a dependency.
      # Bumping kustomize itself has led to using Go versions newer than what's available in the image builder jobs, breaking our builds.
      - dependency-name: "sigs.k8s.io/kustomize/*"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: ":seedling:"
    groups:
      dependencies:
        patterns:
          - "*"
